### ISSUE TITLE
Shouldn't be able to push a Pr that doesn't build

### ISSUE THREAD

**Issue by KienHui** [metoolbrigade1208/2025CompetitionRobot#38]
GitHub needs to try to build the branch and have it succeed to allow the PR to push. Figure out how to build on GitHub.

**Comment by AwesomeKian09** [comment]
From what I found online, It seems like we need to create a Github Actions Workflow so it will automatically check. We can create a workflow folder inside of .github and then we put a .yml file in there to define the workflow. Here is some AI generated code I got for that file: 

```

name: Build Check

on:
  pull_request:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Change as needed (e.g., macos-latest, windows-latest)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment (optional)
        # Example: Setup Node.js, Python, Java, etc.
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Change to your required version

      - name: Install dependencies
        run: npm install  # Adjust for your project (e.g., `pip install -r requirements.txt`)

      - name: Build project
        run: npm run build  # Adjust as needed (e.g., `make build`, `cargo build`, etc.)

```
